import type { ContactInfo, QuickActionItem, TranslationDict } from "../types";

export const translations: TranslationDict = {
  en: {
    nav_home: "Home",
    nav_services: "Services",
    nav_products: "Products",
    nav_staff: "Staff",
    nav_contact: "Contact",
    hero_title: "SASIDHAR GAS AGENCY (HP)",
    cta_chat: "Chat Now for Help",
    btn_call: "Call",
    btn_wa: "WhatsApp",
    quick_actions_title: "Quick Actions",
    tile_new_conn: "New LPG Connection",
    tile_complaint: "Complaint / Issue",
    tile_delivery: "Estimated Delivery",
    tile_buy: "Buy Products",
    tile_staff: "Delivery boy contact details",
    tile_safety: "Safety Guide",
    delivery_title: "Delivery & Timings",
    timings_head: "🕒 Office Timings",
    sunday_closed: "Sunday: Closed",
    delivery_note_head: "🚚 Delivery Estimates",
    delivery_note_body:
      "Estimated delivery depends on your area and booking day. Routes are scheduled weekly.",
    btn_check_delivery: "Check My Delivery Date",
    timings_section_heading: "Office Timings",
    timings_line: "Mon - Sat: 9:30 AM - 7:00 PM",
    products_title: "Buy Accessories",
    prod_stove: "Gas Stove / Hoses",
    prod_desc: "High quality stoves, safety hoses, and lighters available.",
    btn_enquire: "Enquire on WhatsApp",
    staff_title: "Staff Contacts",
    office_staff: "Office Staff",
    delivery_staff: "Delivery Staff",
    safety_title: "Safety First",
    safe_1: "Keep cylinder upright.",
    safe_2: "Check rubber tube regularly.",
    safe_3: "Don't store near flames.",
    safe_4: "Turn off regulator at night.",
    emergency_label: "EMERGENCY: Gas Leak?",
    leak_steps: "Open windows. Do not use electric switches. Evacuate.",
    contact_title: "Contact Us",
    chat_welcome: "Hello! How can I help you today?",
    social_title: "Stay Connected With Us",
    social_subtitle: "Follow Sasidhar Gas Agency for updates and announcements",
    refill_heading: "HP Gas Refill Booking Options",
    refill_subheading: "Choose the quickest way to book your HP Gas refill",
    refill_card1_title: "HP Pay Mobile App",
    refill_card1_sub: "Book quickly via the official app",
    refill_card2_title: "WhatsApp Booking",
    refill_card2_sub: 'Say "Hi" from your registered mobile',
    refill_card3_title: "HP ANY Time (IVRS)",
    refill_card3_sub: "Dial from your registered mobile",
    refill_other_heading: "Other Booking Options",
    refill_missed: "Missed Call: Just give a missed call on 94936 02222 from your registered mobile number.",
    refill_website: "Website: www.myhpgas.in",
    refill_umang: "Umang Mobile App: Available under Play Store for Android & IOS.",
    refill_wallets: "Amazon, Paytm, PhonePe or any BBPS enabled Wallets/ Bank Apps under pay bill section/utilities.",
    refill_csc: "Customer Service Centers: Nearby CSC can be contacted for booking.",
    refill_distributor: "At your HP Gas Distributorship: Sasidhar Gas Agency (HP) +91 8649255551",
  },
  te: {
    nav_home: "హోమ్",
    nav_services: "సేవలు",
    nav_products: "ఉత్పత్తులు",
    nav_staff: "సిబ్బంది",
    nav_contact: "సంప్రదించండి",
    hero_title: "శశిధర్ గ్యాస్ ఏజెన్సీ (HP)",
    cta_chat: "సహాయం కోసం చాట్ చేయండి",
    btn_call: "కాల్ చేయండి",
    btn_wa: "వాట్సాప్",
    quick_actions_title: "త్వరిత సేవలు",
    tile_new_conn: "కొత్త LPG కనెక్షన్",
    tile_complaint: "ఫిర్యాదు / సమస్య",
    tile_delivery: "డెలివరీ అంచనా",
    tile_buy: "ఉత్పత్తులు కొనండి",
    tile_staff: "డెలివరీ బాయ్ సంప్రదింపు వివరాలు",
    tile_safety: "భద్రతా సూచనలు",
    delivery_title: "డెలివరీ & సమయాలు",
    timings_head: "🕒 ఆఫీసు సమయాలు",
    sunday_closed: "ఆదివారం: సెలవు",
    delivery_note_head: "🚚 డెలివరీ అంచనా",
    delivery_note_body: "మీ ఏరియా మరియు బుకింగ్ రోజును బట్టి డెలివరీ ఉంటుంది.",
    btn_check_delivery: "డెలివరీ వివరాలు చాట్ లో అడగండి",
    timings_section_heading: "ఆఫీస్ సమయాలు",
    timings_line: "సోమ - శని: ఉదయం 9:30 - సాయంత్రం 7:00",
    products_title: "పరికరాలు కొనండి",
    prod_stove: "గ్యాస్ స్టవ్ / పైపు / రెగ్యులేటర్",
    prod_desc: "లభ్యత మారవచ్చు. వాట్సాప్‌లో నిర్ధారించండి.",
    btn_enquire: "వాట్సాప్‌లో అడగండి",
    staff_title: "సిబ్బంది వివరాలు",
    office_staff: "ఆఫీసు సిబ్బంది",
    delivery_staff: "డెలివరీ సిబ్బంది",
    safety_title: "భద్రత ముఖ్యం",
    safe_1: "సిలిండర్ నిలువుగా ఉంచండి.",
    safe_2: "రబ్బరు ట్యూబ్‌ను తరచుగా తనిఖీ చేయండి.",
    safe_3: "మంటల దగ్గర ఉంచవద్దు.",
    safe_4: "వాడనప్పుడు రెగ్యులేటర్ ఆఫ్ చేయండి.",
    emergency_label: "అత్యవసరం: గ్యాస్ లీక్ / మంటలు",
    leak_steps:
      "కిటికీలు తెరవండి, స్విచ్‌లు వేయవద్దు, రెగ్యులేటర్ ఆపి బయటకు రండి.",
    contact_title: "మమ్మల్ని సంప్రదించండి",
    chat_welcome: "నమస్కారం! నేను మీకు ఎలా సహాయపడగలను?",
    social_title: "మాతో కనెక్ట్‌గా ఉండండి",
    social_subtitle: "తాజా అప్‌డేట్స్ మరియు ప్రకటనల కోసం ససిధర్ గ్యాస్ ఏజెన్సీని ఫాలో అవండి",
    refill_heading: "HP గ్యాస్ రీఫిల్ బుకింగ్ ఎంపికలు",
    refill_subheading: "మీ HP గ్యాస్ రీఫిల్‌ను బుక్ చేయడానికి త్వరిత మార్గాన్ని ఎంచుకోండి",
    refill_card1_title: "HP Pay మొబైల్ యాప్",
    refill_card1_sub: "ఆధికారిక యాప్ ద్వారా త్వరగా బుక్ చేయండి",
    refill_card2_title: "WhatsApp బుకింగ్",
    refill_card2_sub: "మీ రిజిస్టర్డ్ మొబైల్ నుంచి “Hi” అని పంపండి",
    refill_card3_title: "HP ANY Time (IVRS)",
    refill_card3_sub: "మీ రిజిస్టర్డ్ మొబైల్ నుంచి డయల్ చేయండి",
    refill_other_heading: "ఇతర బుకింగ్ ఎంపికలు",
    refill_missed:
      "మిస్డ్ కాల్: మీ రిజిస్టర్డ్ మొబైల్ నంబర్ నుంచి 94936 02222 కు మిస్డ్ కాల్ ఇవ్వండి.",
    refill_website: "వెబ్‌సైట్: www.myhpgas.in",
    refill_umang: "UMANG మొబైల్ యాప్: Android & iOS కోసం Play Store లో అందుబాటులో ఉంటుంది.",
    refill_wallets:
      "Amazon, Paytm, PhonePe లేదా BBPS ఎనేబుల్ చేసిన వాలెట్లు/బ్యాంక్ యాప్‌లలో pay bill / utilities సెక్షన్ ద్వారా.",
    refill_csc: "కస్టమర్ సర్వీస్ సెంటర్లు: బుకింగ్ కోసం సమీపంలోని CSC ను సంప్రదించండి.",
    refill_distributor:
      "మీ HP గ్యాస్ డిస్ట్రిబ్యూటర్ వద్ద: Sasidhar Gas Agency (HP) +91 8649255551",
  },
};

export const schemeImages: string[] = [
  "https://storage.googleapis.com/sasidharstorage/schemes/1493313-gas-cyllinder.webp",
  "https://storage.googleapis.com/sasidharstorage/schemes/1542565-pm-ujjwala-yojana.webp",
  "https://storage.googleapis.com/sasidharstorage/schemes/25-Lakh-Free-LPG-Connections-with-%E2%82%B9300-Subsidy.webp",
  "https://storage.googleapis.com/sasidharstorage/schemes/550588364_1088868286749924_949336914067018364_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/schemes/552257804_1088868290083257_3358908604320363123_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/schemes/AP-Free-Gas-Cylinder-Booking-2024.webp",
  "https://storage.googleapis.com/sasidharstorage/schemes/Screenshot%202026-01-23%20192607.png",
  "https://storage.googleapis.com/sasidharstorage/schemes/andhra-pradesh-gas-cylinder-scheme.webp",
  "https://storage.googleapis.com/sasidharstorage/schemes/deepamschemeamount_0.avif",
  "https://storage.googleapis.com/sasidharstorage/schemes/pradhan-mantri-ujjwala-yojana-scheme-details.avif",
];

export const agencyImages: string[] = [
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180624-WA0011.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180711-WA0006.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180824-WA0003.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180825-WA0008.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180825-WA0012.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180825-WA0022.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180825-WA0034.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20180913-WA0029.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181031-WA0026.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181031-WA0041.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181103-WA0123.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181103-WA0135.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181106-WA0003.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG-20181113-WA0022.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20180824_081658.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20181027_165451.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20181222_121010.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20190209_163503.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20190209_163640.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20191123_171652.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20200829_130457.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20250305_173343.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/IMG_20250305_173624.jpg",
  "https://storage.googleapis.com/sasidharstorage/middle/SRI_3344.JPG",
  "https://storage.googleapis.com/sasidharstorage/middle/ai.png",
  "https://storage.googleapis.com/sasidharstorage/middle/drivers.webp",
  "https://storage.googleapis.com/sasidharstorage/middle/image%20(3).png",
  "https://storage.googleapis.com/sasidharstorage/middle/staff.webp",
];

export const productImages: string[] = [
  "https://storage.googleapis.com/sasidharstorage/products/120435289_1080297645720284_94431934159470219_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/19kg-hp-lpg-commercial-gas-cylinder-1000x1000.webp",
  "https://storage.googleapis.com/sasidharstorage/products/1_19.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/518065166_17988397556829708_5969311771541109093_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/518724999_17988837659829708_3712006312649372710_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/531810792_17992399985829708_7026906141849726201_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/541558014_17994107399829708_1958564444624536788_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/543589502_17994617414829708_6278111146010002928_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/550777593_17996017517829708_3553496675478636286_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/606034564_18007724081829708_6727344626587496602_n.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/71IK-J6tcqS._SL1500_.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/FB_IMG_1618830910661.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/Turbo_1%20(1)_0.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/butterfly-smart-glass-top-2-burner-gas-stove.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/pipe%202.png",
  "https://storage.googleapis.com/sasidharstorage/products/pipe.png",
  "https://storage.googleapis.com/sasidharstorage/products/stove%202.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/stove%203.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/stove%204.jpg",
  "https://storage.googleapis.com/sasidharstorage/products/stove%205.jpg",
];

export const quickActions: QuickActionItem[] = [
  {
    icon: "🔥",
    labelKey: "tile_new_conn",
    href: null,
    topic: "new_connection",
  },
  { icon: "⚠️", labelKey: "tile_complaint", href: null, topic: "complaint" },
    { icon: "🚚", labelKey: "tile_delivery", href: null, topic: "delivery" },
    { icon: "🛒", labelKey: "tile_buy", href: "#products", topic: null },
    { icon: "📞", labelKey: "tile_staff", href: "#staff", topic: null },
    { icon: "🧯", labelKey: "tile_safety", href: "#safety", topic: null },
  ];

export const safetyTips: string[] = ["safe_1", "safe_2", "safe_3", "safe_4"];

export const contactInfo: ContactInfo = {
  name: "Sasidhar Gas Agency (HP)",
  address: "D.NO. 15-223, Main Road, near police station",
  city: "Piduguralla",
  state: "Andhra Pradesh",
  postalCode: "522413",
  officeNumber: "+918649255551",
  whatsappNumber: "+919866195074",
  fireStationNumber: "+919642770955",
  mapsUrl: "https://maps.app.goo.gl/1HkGRZBqhADZGNHM6",
};

export const HP_LOGO_URL =
  "https://storage.googleapis.com/sasidharstorage/Head/logo.webp";

export const PRODUCT_IMAGE_URL =
  "https://storage.googleapis.com/sasidharstorage/products/FB_IMG_1618830910661.jpg";
